// This file is autogenerated. Changes will be overwritten.
#include "33QJQDC7XV/moc_authorizationwindow.cpp"
#include "EWIEGA46WW/moc_appointmentwindow.cpp"
#include "EWIEGA46WW/moc_createwindow.cpp"
#include "EWIEGA46WW/moc_doctorclientwindow.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_redactwindow.cpp"
#include "EWIEGA46WW/moc_registerwindow.cpp"
